name: EEGToTextOpenVoc
channels:
  - pytorch
  - dglteam
  - nvidia
  - conda-forge
  - anaconda
  - intel
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - attrs=21.2.0=pyhd3eb1b0_0
  - autopep8=1.6.0=pyhd3eb1b0_1
  - blas=1.0=mkl
  - brotlipy=0.7.0=py38h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.17.1=h27cfd23_0
  - ca-certificates=2022.10.11=h06a4308_0
  - catalogue=1.0.0=py38_1
  - certifi=2022.9.24=py38h06a4308_0
  - cffi=1.14.6=py38h400218f_0
  - chardet=4.0.0=py38h06a4308_1003
  - click=8.0.1=pyhd3eb1b0_0
  - conda=4.10.3=py38h578d9bd_0
  - conda-package-handling=1.7.3=py38h27cfd23_1
  - cryptography=3.4.7=py38hd23ed53_0
  - cudatoolkit=11.1.74=h6bb024c_0
  - cycler=0.10.0=py38_0
  - cymem=2.0.5=py38h2531618_0
  - cython-blis=0.4.1=py38h7b6447c_1
  - dbus=1.13.18=hb2f20db_0
  - decorator=5.0.9=pyhd3eb1b0_0
  - dgl-cuda10.2=0.5.2=py38_0
  - expat=2.4.1=h2531618_2
  - ffmpeg=4.2.2=h20bf706_0
  - fontconfig=2.13.1=h6c09931_0
  - freetype=2.10.4=h5ab3b9f_0
  - glib=2.69.0=h5202010_0
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.15=he1e5248_0
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - icu=58.2=he6710b0_3
  - idna=2.10=pyhd3eb1b0_0
  - importlib_metadata=3.10.0=hd3eb1b0_0
  - intel-openmp=2021.3.0=h06a4308_3350
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.3.1=py38h2531618_0
  - krb5=1.19.2=hac12032_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libcurl=7.78.0=h0b77cf5_0
  - libedit=3.1.20210216=h27cfd23_1
  - libev=4.33=h7b6447c_0
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=9.3.0=h5101ec6_17
  - libidn2=2.3.2=h7f8727e_0
  - libnghttp2=1.41.0=hf8bcb03_2
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.37=hbc83047_0
  - libssh2=1.9.0=h1ba5d50_1
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h85742a9_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.0.3=h1bed415_2
  - libuv=1.40.0=h7b6447c_0
  - libvpx=1.7.0=h439df22_0
  - libwebp-base=1.2.0=h27cfd23_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.12=h03d6c58_0
  - lz4-c=1.9.3=h295c915_1
  - matplotlib=3.3.2=0
  - matplotlib-base=3.3.2=py38h817c723_0
  - mkl=2020.2=256
  - mkl-service=2.3.0=py38he904b0f_0
  - mkl_fft=1.3.0=py38h54f3939_0
  - mkl_random=1.1.1=py38h0573a6f_0
  - murmurhash=1.0.5=py38h2531618_0
  - ncurses=6.2=he6710b0_1
  - nettle=3.7.3=hbbd107a_1
  - networkx=2.5=py_0
  - ninja=1.10.2=hff7bd54_1
  - olefile=0.46=py_0
  - openh264=2.1.0=hd408876_0
  - openjpeg=2.3.0=h05c96fa_1
  - openssl=1.1.1q=h7f8727e_0
  - pcre=8.45=h295c915_0
  - pip=21.0.1=py38h06a4308_0
  - plac=0.9.6=py38_1
  - preshed=3.0.5=py38h2531618_4
  - pycodestyle=2.10.0=py38h06a4308_0
  - pycosat=0.6.3=py38h7b6447c_1
  - pycparser=2.20=py_2
  - pycurl=7.43.0.6=py38h1ba5d50_0
  - pymongo=3.11.2=py38h2531618_0
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyqt=5.9.2=py38h05f1152_4
  - pyrsistent=0.17.3=py38h7b6447c_0
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.5=h7579374_1
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.8=2_cp38
  - qt=5.9.7=h5867ecd_1
  - readline=8.1=h27cfd23_0
  - requests=2.25.1=pyhd3eb1b0_0
  - ruamel.yaml=0.17.10=py38h497a2fe_0
  - ruamel.yaml.clib=0.2.2=py38h497a2fe_2
  - ruamel_yaml=0.15.100=py38h27cfd23_0
  - setuptools=52.0.0=py38h06a4308_0
  - sip=4.19.13=py38he6710b0_0
  - six=1.16.0=pyhd3eb1b0_0
  - spacy=2.3.2=py38hfd86e86_0
  - sqlite=3.36.0=hc218d9a_0
  - srsly=1.0.5=py38h2531618_0
  - thinc=7.4.1=py38hfd86e86_0
  - threadpoolctl=2.2.0=pyhbf3da8f_0
  - tk=8.6.10=hbc83047_0
  - toml=0.10.2=pyhd3eb1b0_0
  - torchaudio=0.9.0=py38
  - urllib3=1.26.6=pyhd3eb1b0_1
  - wasabi=0.8.2=pyhd3eb1b0_0
  - wheel=0.37.0=pyhd3eb1b0_0
  - x264=1!157.20191217=h7b6447c_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zipp=3.5.0=pyhd3eb1b0_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=haebb681_0
  - pip:
      - absl-py==1.4.0
      - accelerate==0.17.1
      - aiohttp==3.8.4
      - aiosignal==1.3.1
      - antlr4-python3-runtime==4.9.3
      - anyio==3.6.2
      - appdirs==1.4.4
      - argon2-cffi==21.3.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.2.3
      - asttokens==2.2.1
      - async-timeout==4.0.2
      - backcall==0.2.0
      - beautifulsoup4==4.11.2
      - bert-score==0.3.13
      - black==23.1.0
      - bleach==6.0.0
      - boto3==1.26.94
      - botocore==1.29.94
      - brevitas==0.8.0
      - cachetools==5.3.0
      - charset-normalizer==3.1.0
      - cloudpickle==2.2.1
      - cmake==3.26.0
      - comm==0.1.2
      - dataclasses-json==0.5.7
      - datasets==2.10.1
      - debugpy==1.6.6
      - defusedxml==0.7.1
      - dependencies==2.0.1
      - detectron2==0.6
      - dill==0.3.6
      - executing==1.2.0
      - fastjsonschema==2.16.2
      - fasttext==0.9.2
      - filelock==3.9.0
      - fqdn==1.5.1
      - frozenlist==1.3.3
      - fsspec==2023.3.0
      - fst-pso==1.8.1
      - funcy==1.18
      - future==0.18.3
      - fuzzy-match==0.0.1
      - fuzzytm==2.0.5
      - fvcore==0.1.5.post20221221
      - gensim==4.3.0
      - geojson==2.5.0
      - google-auth==2.16.0
      - google-auth-oauthlib==0.4.6
      - greenlet==2.0.2
      - grpcio==1.51.1
      - h5py==2.10.0
      - huggingface-hub==0.13.2
      - hydra-core==1.3.1
      - importlib-metadata==6.0.0
      - importlib-resources==5.10.2
      - inflect==6.0.2
      - inquirerpy==0.3.4
      - iopath==0.1.9
      - ipykernel==6.21.2
      - ipython==8.10.0
      - ipython-genutils==0.2.0
      - ipywidgets==8.0.4
      - isoduration==20.11.0
      - jedi==0.18.2
      - jinja2==3.1.2
      - jmespath==1.0.1
      - joblib==1.2.0
      - jsonpointer==2.3
      - jsonschema==4.17.3
      - jupyter==1.0.0
      - jupyter-client==8.0.2
      - jupyter-console==6.5.1
      - jupyter-core==5.2.0
      - jupyter-events==0.6.3
      - jupyter-server==2.3.0
      - jupyter-server-terminals==0.4.4
      - jupyterlab-pygments==0.2.2
      - jupyterlab-widgets==3.0.5
      - langchain==0.0.125
      - lit==15.0.7
      - mako==1.2.4
      - markdown==3.4.1
      - markupsafe==2.1.2
      - marshmallow==3.19.0
      - marshmallow-enum==1.5.1
      - matplotlib-inline==0.1.6
      - miniful==0.0.6
      - mistune==2.0.5
      - mpmath==1.3.0
      - multidict==6.0.4
      - multiprocess==0.70.14
      - mypy-extensions==1.0.0
      - nbclassic==0.5.1
      - nbclient==0.7.2
      - nbconvert==7.2.9
      - nbformat==5.7.3
      - nest-asyncio==1.5.6
      - nltk==3.8.1
      - notebook==6.5.2
      - notebook-shim==0.2.2
      - numexpr==2.8.4
      - numpy==1.23.5
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - openai==0.27.2
      - opt-einsum==3.3.0
      - packaging==23.0
      - pandas==1.5.3
      - pandocfilters==1.5.0
      - parso==0.8.3
      - pathspec==0.11.0
      - pexpect==4.8.0
      - pfzy==0.3.4
      - pickleshare==0.7.5
      - pillow==9.4.0
      - pkgutil-resolve-name==1.3.10
      - platformdirs==3.0.0
      - plotly==5.13.0
      - portalocker==2.7.0
      - powerlaw==1.5
      - prometheus-client==0.16.0
      - prompt-toolkit==3.0.36
      - protobuf==3.20.3
      - psutil==5.9.4
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyarrow==11.0.0
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pybind11==2.10.4
      - pycocotools==2.0.6
      - pycuda==2022.2.2
      - pydantic==1.10.6
      - pyfume==0.2.25
      - pygments==2.14.0
      - pyldavis==3.3.1
      - pyowm==3.3.0
      - pyro-api==0.1.2
      - pyro-ppl==1.8.4
      - python-graphviz==0.20.1
      - python-json-logger==2.0.6
      - pytools==2022.1.14
      - pytorch-pretrained-bert==0.6.2
      - pytz==2022.7.1
      - pyyaml==6.0
      - pyzmq==25.0.0
      - qtconsole==5.4.0
      - qtpy==2.3.0
      - quant-cuda==0.0.0
      - regex==2022.10.31
      - requests-oauthlib==1.3.1
      - responses==0.18.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rouge==1.0.1
      - rouge-score==0.1.2
      - rsa==4.9
      - s3transfer==0.6.0
      - sacremoses==0.0.53
      - safetensors==0.3.0
      - scikit-learn==1.2.1
      - scipy==1.10.1
      - send2trash==1.8.0
      - sentence-transformers==2.2.2
      - sentencepiece==0.1.97
      - simpful==2.10.0
      - sklearn==0.0.post1
      - smart-open==6.3.0
      - sniffio==1.3.0
      - soupsieve==2.4
      - sqlalchemy==1.4.47
      - stack-data==0.6.2
      - sympy==1.11.1
      - tabulate==0.9.0
      - tenacity==8.2.1
      - tensorboard==2.12.0
      - tensorboard-data-server==0.7.0
      - tensorboard-plugin-wit==1.8.1
      - termcolor==2.2.0
      - terminado==0.17.1
      - tinycss2==1.2.1
      - tokenizers==0.13.2
      - tomli==2.0.1
      - torch==1.13.1
      - torch-summary==1.4.5
      - torchcontrib==0.0.2
      - torchvision==0.15.1
      - torchviz==0.0.2
      - tornado==6.2
      - tqdm==4.65.0
      - traitlets==5.9.0
      - transformers==4.28.0.dev0
      - triton==2.0.0
      - typing-extensions==4.5.0
      - typing-inspect==0.8.0
      - uri-template==1.2.0
      - wcwidth==0.2.6
      - webcolors==1.12
      - webencodings==0.5.1
      - websocket-client==1.5.1
      - weightwatcher==0.7.1.5
      - werkzeug==2.2.3
      - widgetsnbextension==4.0.5
      - wordcloud==1.8.2.2
      - xxhash==3.2.0
      - yacs==0.1.8
      - yarl==1.8.2
prefix: /home/hamza/miniconda3/envs/EEGToTextOpenVoc
